# Generated by Django 5.2.17 on 2026-08-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_api', '0006_upsert_and_archive'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trackingpoint',
            name='live_api_tr_competi_5a0a2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackingpoint',
            name='tracking_task_time_idx',
        ),
    ]
